### PR TITLE
languages: add Julia

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
I didn't test this locally because I didn't have time to set up isolate on my machine, so I was counting on CI to run the tests. Looks like it didn't run though.

**Comment by lportemo** [comment]
Thanks for the pull request ! I will try to fix the CI :)

**Comment by LeSeulArtichaut** [comment]
@lportemo friendly ping :)
Can I do anything to help with this?

**Comment by Kochise** [comment]
Try it on Docker.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/services/camisole/-/merge_requests/58

**Pull request closed without merging**
